package jb.openware.app.nativeAds

import android.graphics.Typeface
import android.graphics.drawable.ColorDrawable

class NativeTemplateStyle(
    var callToActionTextTypeface: Typeface? = null,
    var callToActionTextSize: Float = 0f,
    var callToActionTypefaceColor: Int? = null,
    var callToActionBackgroundColor: ColorDrawable? = null,

    var primaryTextTypeface: Typeface? = null,
    var primaryTextSize: Float = 0f,
    var primaryTextTypefaceColor: Int? = null,
    var primaryTextBackgroundColor: ColorDrawable? = null,

    var secondaryTextTypeface: Typeface? = null,
    var secondaryTextSize: Float = 0f,
    var secondaryTextTypefaceColor: Int? = null,
    var secondaryTextBackgroundColor: ColorDrawable? = null,

    var tertiaryTextTypeface: Typeface? = null,
    var tertiaryTextSize: Float = 0f,
    var tertiaryTextTypefaceColor: Int? = null,
    var tertiaryTextBackgroundColor: ColorDrawable? = null,

    var mainBackgroundColor: ColorDrawable? = null
) {

    // All Java-style getters are automatically generated by Kotlin:
    // getCallToActionTextTypeface(), getPrimaryTextTypefaceColor(), etc.
    // So existing Java usage won't break.

    class Builder {
        private val styles = NativeTemplateStyle()

        fun withCallToActionTextTypeface(typeface: Typeface) = apply {
            styles.callToActionTextTypeface = typeface
        }

        fun withCallToActionTextSize(size: Float) = apply {
            styles.callToActionTextSize = size
        }

        fun withCallToActionTypefaceColor(color: Int) = apply {
            styles.callToActionTypefaceColor = color
        }

        fun withCallToActionBackgroundColor(colorDrawable: ColorDrawable) = apply {
            styles.callToActionBackgroundColor = colorDrawable
        }

        fun withPrimaryTextTypeface(typeface: Typeface) = apply {
            styles.primaryTextTypeface = typeface
        }

        fun withPrimaryTextSize(size: Float) = apply {
            styles.primaryTextSize = size
        }

        fun withPrimaryTextTypefaceColor(color: Int) = apply {
            styles.primaryTextTypefaceColor = color
        }

        fun withPrimaryTextBackgroundColor(colorDrawable: ColorDrawable) = apply {
            styles.primaryTextBackgroundColor = colorDrawable
        }

        fun withSecondaryTextTypeface(typeface: Typeface) = apply {
            styles.secondaryTextTypeface = typeface
        }

        fun withSecondaryTextSize(size: Float) = apply {
            styles.secondaryTextSize = size
        }

        fun withSecondaryTextTypefaceColor(color: Int) = apply {
            styles.secondaryTextTypefaceColor = color
        }

        fun withSecondaryTextBackgroundColor(colorDrawable: ColorDrawable) = apply {
            styles.secondaryTextBackgroundColor = colorDrawable
        }

        fun withTertiaryTextTypeface(typeface: Typeface) = apply {
            styles.tertiaryTextTypeface = typeface
        }

        fun withTertiaryTextSize(size: Float) = apply {
            styles.tertiaryTextSize = size
        }

        fun withTertiaryTextTypefaceColor(color: Int) = apply {
            styles.tertiaryTextTypefaceColor = color
        }

        fun withTertiaryTextBackgroundColor(colorDrawable: ColorDrawable) = apply {
            styles.tertiaryTextBackgroundColor = colorDrawable
        }

        fun withMainBackgroundColor(colorDrawable: ColorDrawable) = apply {
            styles.mainBackgroundColor = colorDrawable
        }

        fun build(): NativeTemplateStyle = styles
    }
}
